apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim-cloudcamp
  namespace: microblog
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 10Gi